#
# User-defined substitutions:
#   _CLOUDSDK_COMPUTE_ZONE
#   _CLOUDSDK_CONTAINER_CLUSTER
#   _GITHUB_USERNAME
#   _KMS_KEY
#   _KMS_KEYRING
#

steps:
  # Generate a kubeconfig file
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        CLUSTER=$$(gcloud config get-value container/cluster)
        PROJECT=$$(gcloud config get-value core/project)
        ZONE=$$(gcloud config get-value compute/zone)
      
        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"
    volumes:
      - name: 'kube'
        path: /kube

  # Retrieve and decrypt the GitHub Hub configuration. 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gsutil cp gs://${PROJECT_ID}-trends-configs/hub.enc hub.enc

        gcloud kms decrypt \
          --ciphertext-file=hub.enc \
          --plaintext-file=/config/hub \
          --location=global \
          --keyring=${_KMS_KEYRING} \
          --key=${_KMS_KEY}
    volumes:
      - name: 'config'
        path: /config

  # Update the kompose deployment.
  - name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.1.0/kompose-linux-amd64 -o kompose
        chmod +x kompose
        mv ./kompose /usr/local/bin/kompose
        kompose down
        kompose up
    volumes:
      - name: 'kube'
        path: /kube

  # Create a pull request on the ${_GITHUB_USERNAME}/trends-infrastructure-production repo
  # to update the trends deployment configuration.
  - name: 'gcr.io/hightowerlabs/hub'
    env:
      - 'HUB_CONFIG=/config/hub'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Extract the container image from the qa trends docker-compose.yaml file.
        pip install --upgrade setuptools
        python -m easy_install pyyaml
        CONTAINER_IMAGE=$(python -c "import yaml; print(yaml.load(open('docker-compose.yaml'))['services']['web']['image'])")

        ACTIVE_ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")

        hub config --global credential.https://github.com.helper /usr/local/bin/hub-credential-helper
        hub config --global hub.protocol https
        hub config --global user.email "$${ACTIVE_ACCOUNT}"
        hub config --global user.name "Google Container Builder"


        # Clone the ${_GITHUB_USERNAME}/trends-infrastructure-production repo
        # and patch the trends deployment container image.
        hub clone "https://github.com/${_GITHUB_USERNAME}/trends-infrastructure-production.git"

        sed -i "s%gcr.io/${PROJECT_ID}/trends.*%$${CONTAINER_IMAGE}%g" docker-compose.yaml

        mv docker-compose.yaml trends-infrastructure-production/docker-compose.yaml
        # Change to the trends-infrastructure-production directory.
        cd trends-infrastructure-production

        # commit the local changes, then issue a pull request.
        git checkout -b update-deployment-${BUILD_ID}

        hub add docker-compose.yaml

        hub commit -F- <<EOF
        Update the trends deployment

        This commit updates the trends deployment container image to:

            $${CONTAINER_IMAGE}

        Build ID: ${BUILD_ID}
        EOF

        hub push origin update-deployment-${BUILD_ID}

        # Create a pull request to the ${_GITHUB_USERNAME}/trends-infrastructure-production repo.
        hub pull-request -F- <<EOF
        Update the trends deployment

        This commit updates the trends deployment container image to:

            $${CONTAINER_IMAGE}

        Build ID: ${BUILD_ID}
        EOF
    volumes:
      - name: 'config'
        path: /config
      - name: 'kube'
        path: /kube
